### ISSUE TITLE
chef 12 compatibility

### ISSUE THREAD

**Issue by blueharford** [bmarini/knife-inspect#36]
any plans or ETA for chef12 compatibility?

**Comment by gregkare** [comment]
Hi! I haven't switched to Chef 12 yet and I haven't looked at what needs to be done to make it compatible with Chef 12 (if anything). A pull request would be great. If no one does one I'll try to take care of it in the next few weeks.

**Comment by gregkare** [comment]
That was easier than I thought.

@blueharford Can you confirm that the `chef_12` branch works for you? If so I'll release it

**Comment by blueharford** [comment]
@gregkare so i installed it. and i cant call it... its not registering like previous versions

**Comment by gregkare** [comment]
@blueharford Can you post a stacktrace of the problem as a Gist? How are you installing the version in the chef_12 branch, using Bundler?

**Comment by blueharford** [comment]
there is no stack trace, i just do a gem bundle to make the gem then gem install --local knife-inspect-12.0.gem

it installs it, and shows in gem list. but when you run a gem knife inspect. it comes up as a invalid knife command.

**Comment by blueharford** [comment]
@gregkare but when i install 11.1 it errors out, just doesnt skip over

/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-inspect-0.11.1, because chef-12.0.3 conflicts with chef (<= 12, >= 10) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.11.1/lib/chef/knife/cookbook_inspect.rb:2:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife/core/subcommand_loader.rb:35:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife/core/subcommand_loader.rb:35:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife/core/subcommand_loader.rb:35:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife/core/subcommand_loader.rb:35:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:126:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:207:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/embedded/bin/knife:23:in `load'
	from /opt/chefdk/embedded/bin/knife:23:in `<main>'
jseidelmbpr:pkg jseidel$

**Comment by blueharford** [comment]
@bmarini any update?

**Comment by gregkare** [comment]
Sorry, I forgot to answer. Your logs says `chef (<= 12, >= 10)` so it looks like you're not installing the knife-inspect from the chef_12 branch

**Comment by gregkare** [comment]
@blueharford I've just released [knife-inspect 0.12.0](https://rubygems.org/gems/knife-inspect/versions/0.12.0), which supports Chef 12. Tell me if you find issues with it, thanks in advance :)

**Comment by blueharford** [comment]
@gregkare it works, your the man!
