### ISSUE TITLE
"inspect" subcommand not working

### ISSUE THREAD

**Issue by arielrolfo** [bmarini/knife-inspect#44]
Hi, I've just installed and tried to use as "knife inspect" but the inspect subcommand doesn't seem to be recognized in knife, see my evidences:

[ariel@oc5856325724 ~]$ **gem list | grep -i inspec**
knife-inspect (0.14.0)

[ariel@oc5856325724 ~]$ **gem env**
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/ariel/.rvm/gems/ruby-2.2.1
  - RUBY EXECUTABLE: /home/ariel/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/ariel/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /home/ariel/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/ariel/.rvm/rubies/ruby-2.2.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/ariel/.rvm/gems/ruby-2.2.1
     - /home/ariel/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/lib64/qt-3.3/bin
     - /home/ariel/.rvm/gems/ruby-2.2.1/bin
     - /home/ariel/.rvm/gems/ruby-2.2.1@global/bin
     - /home/ariel/.rvm/rubies/ruby-2.2.1/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
     - /bin
     - /sbin
     - /home/ariel/.rvm/bin
     - /home/ariel/.rvm/bin
     - /home/ariel/.local/bin
     - /home/ariel/bin
     - /usr/kerberos/bin
     - /home/ariel/.rvm/bin

**[ariel@oc5856325724 ~]$ knife inspect
FATAL: Cannot find subcommand for: 'inspect'
Available subcommands: (for details, knife SUB-COMMAND --help)**

**Comment by gregkare** [comment]
Hi,

Which version of chef do you have installed? Is it a gem version or Chef DK?

Thanks

**Comment by arielrolfo** [comment]
Hi Greg, I was able to sort it out by rebooting the machine, it could be documented some how.

**Comment by gregkare** [comment]
It sounds like your path contained a different knife binary, this is probably why rebooting fixed it. Closing this one
